#!/bin/sh

MSG=`awk '{printf("%s",$0)}' $1`
if [[ $MSG =~ ^(feat|fix|test|refactor|docs|style|chore)\(.*\):.*$ ]]; then
    if [[ $MSG =~ ^(fix)\(.*\):.*$ ]]; then
        res=$(echo $MSG | awk -F '# Please' '{print $1}' |grep -E "#[0-9]+")
        if [[ -z "$res" ]]; then
            echo -e "\033[31m Error: when you commit message start with fix, \033[m"
            echo -e "\033[31m you should mention the issue number. \033[m"
            echo -e "\033[31m fix(user): fix user login bug (#123) \033[m"
            exit 1
        fi
    fi
    echo -e "\033[32m commit success! \033[0m"
else
    echo -e "\033[31m Error: the commit message is irregular \033[m"
    echo -e "\033[31m Error: type must be one of [feat,fix,docs,style,refactor,test,chore] \033[m"
    echo -e "\033[31m eg: feat(user): add the user login \033[m"
    exit 1
fi
